### ISSUE TITLE
ERROR: Couldn't find env file

### ISSUE THREAD

**Issue by cnwpdb** [Oritz/Dockerizing-SQLiScanner#1]
作者辛苦了
ERROR: Couldn't find env file: /root/h/Dockerizing-SQLiScanner/.env
   缺少这个文件,
是不是要复制https://github.com/realpython/dockerizing-django/blob/master/.env  这个呢?

**Comment by Oritz** [comment]
嗯，差不多，上次 push 的时候不小心把 .env 删掉了，已经加上了。
